# Generated by Django 6.0 on 2025-12-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the technique (e.g., 'Armbar from Guard')", max_length=200)),
                ('category', models.CharField(choices=[('submissions', 'Submissions'), ('escapes', 'Escapes'), ('sweeps', 'Sweeps'), ('passes', 'Guard Passes'), ('takedowns', 'Takedowns'), ('positions', 'Positions')], help_text='Type of technique', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Skill level required', max_length=20)),
                ('youtube_url', models.URLField(help_text='Full YouTube URL', max_length=500)),
                ('description', models.TextField(help_text='Detailed explanation of the technique')),
                ('position', models.CharField(choices=[('guard', 'Guard'), ('closed_guard', 'Closed Guard'), ('open_guard', 'Open Guard'), ('half_guard', 'Half Guard'), ('mount', 'Mount'), ('side_control', 'Side Control'), ('back_control', 'Back Control'), ('standing', 'Standing'), ('neutral', 'Neutral')], help_text='Starting position', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'ordering': ['category', 'difficulty', 'name'],
            },
        ),
    ]
