# Generated by Django 5.2.8 on 2026-01-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0003_alter_technique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
