# Generated by Django 6.0 on 2025-12-29 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_app", "0002_alter_client_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("street", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.TextField(max_length=2)),
                ("zip", models.IntegerField(max_length=5)),
                ("latitude", models.IntegerField(max_length=2)),
                ("longitude", models.IntegerField(max_length=2)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=models.DateTimeField(default=django.utils.timezone.now)
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Gym",
                        to="user_app.user",
                    ),
                ),
            ],
        ),
    ]
