# Generated by Django 6.0 on 2025-12-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0001_initial"),
        ("user_app", "0002_alter_client_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Gyms",
                to="user_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gym",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gym",
            name="zip",
            field=models.IntegerField(),
        ),
    ]
