# Generated by Django 6.0 on 2025-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_alter_gym_created_by_alter_gym_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
