# Generated by Django 6.0 on 2025-12-30 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0003_alter_gym_created_at_alter_gym_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gym",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gym",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gym",
            name="updated_at",
            field=models.DateTimeField(
                default=models.DateTimeField(default=django.utils.timezone.now)
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="zip",
            field=models.CharField(max_length=5),
        ),
    ]
