# Generated by Django 6.0 on 2025-12-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0001_initial'),
        ('user_app', '0002_alter_client_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user_app.user'),
        ),
    ]
