# Generated by Django 6.0 on 2026-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_client_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
