# Generated by Django 6.0 on 2025-12-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gym_app", "0001_initial"),
        ("user_app", "0002_alter_client_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("gi", models.BooleanField()),
                ("fee", models.DecimalField(decimal_places=2, max_digits=5)),
                ("open_class", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_events",
                        to="gym_app.gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_events",
                        to="user_app.user",
                    ),
                ),
            ],
        ),
    ]
