# Generated by Django 6.0 on 2025-12-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_class',
            field=models.BooleanField(default=False),
        ),
    ]
