# Generated by Django 6.0 on 2026-01-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_id'),
        ('event_app', '0003_alter_event_user'),
    ]

    operations = [
    ]
