# Generated by Django 6.0 on 2026-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0004_merge_0003_alter_event_id_0003_alter_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
